/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/articles/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published articles
         * @description Retrieves a paginated list of published articles sorted by updatedAt descending.
         */
        get: operations["GetArticlesV1"];
        put?: never;
        /**
         * Create a new article
         * @description Creates a new article. Defaults to draft status. Admin only.
         */
        post: operations["PostArticlesV1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/v1/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all articles (admin)
         * @description Retrieves a paginated list of all articles (draft and published) sorted by updatedAt descending. Admin only.
         */
        get: operations["GetArticlesV1Admin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/v1/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a published article by slug
         * @description Retrieves a single published article by its slug.
         */
        get: operations["GetArticlesV1Slug"];
        put?: never;
        post?: never;
        /**
         * Delete an article
         * @description Deletes an article by slug. Admin only.
         */
        delete: operations["DeleteArticlesV1Slug"];
        options?: never;
        head?: never;
        /**
         * Update an article
         * @description Updates an existing article. Admin only.
         */
        patch: operations["PatchArticlesV1Slug"];
        trace?: never;
    };
    "/articles/v1/{slug}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish an article
         * @description Sets an article's status to published and sets the publishedAt timestamp. Admin only.
         */
        post: operations["PostArticlesV1SlugPublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/v1/{slug}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unpublish an article
         * @description Sets an article's status back to draft and clears the publishedAt timestamp. Admin only.
         */
        post: operations["PostArticlesV1SlugUnpublish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Article: {
            /**
             * @description Email of the admin who created the article
             * @example admin@icaa.world
             */
            readonly author: string;
            /** @description Editor.js JSON block data */
            content: Record<string, never>;
            /**
             * Format: date-time
             * @example 2025-08-29T12:00:00Z
             */
            readonly createdAt: string;
            /** @example The ICAA is proud to announce its official launch... */
            excerpt: string;
            /**
             * Format: date-time
             * @description When the article was published, null if draft
             * @example 2025-08-29T12:00:00Z
             */
            readonly publishedAt?: string | null;
            /**
             * @description URL-friendly slug, immutable after creation
             * @example icaa-launch
             */
            slug: string;
            status: components["schemas"]["ArticleStatus"];
            /** @example ICAA Launch Announcement */
            title: string;
            /**
             * Format: date-time
             * @example 2025-08-30T15:30:00Z
             */
            readonly updatedAt: string;
            /** @example 1 */
            readonly version: number;
        };
        /**
         * @example published
         * @enum {string}
         */
        ArticleStatus: "draft" | "published";
        CreateArticleRequest: {
            content: Record<string, never>;
            /** @example The ICAA is proud to announce its official launch... */
            excerpt: string;
            /** @example icaa-launch */
            slug: string;
            /** @example ICAA Launch Announcement */
            title: string;
        };
        Error: {
            code: components["schemas"]["ErrorCode"];
            /** @example An unexpected error occurred. */
            message: string;
        };
        /** @enum {string} */
        ErrorCode: "InternalError" | "LimitOutOfBounds" | "InvalidCursor" | "NotFound" | "EmptyBody" | "InvalidBody" | "AlreadyExists" | "InputValidationError" | "AuthError";
        UpdateArticleRequest: {
            content?: Record<string, never>;
            excerpt?: string;
            /** @example Updated ICAA Launch Announcement */
            title?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetArticlesV1: {
        parameters: {
            query?: {
                /** @description Cursor for pagination */
                cursor?: string;
                /** @description Max number of articles to fetch */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of published articles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Y29uZ3JhdHMsIHlvdSBmb3VuZCB0aGUgZWFzdGVyIGVnZw== */
                        cursor?: string;
                        data: components["schemas"]["Article"][];
                        /** @example true */
                        hasNextPage: boolean;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    PostArticlesV1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Article creation details */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArticleRequest"];
            };
        };
        responses: {
            /** @description Article created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        article: components["schemas"]["Article"];
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Article with this slug already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    GetArticlesV1Admin: {
        parameters: {
            query?: {
                /** @description Cursor for pagination */
                cursor?: string;
                /** @description Max number of articles to fetch */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of all articles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Y29uZ3JhdHMsIHlvdSBmb3VuZCB0aGUgZWFzdGVyIGVnZw== */
                        cursor?: string;
                        data: components["schemas"]["Article"][];
                        /** @example true */
                        hasNextPage: boolean;
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    GetArticlesV1Slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The article. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        article: components["schemas"]["Article"];
                    };
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    DeleteArticlesV1Slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    PatchArticlesV1Slug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** @description Article update details */
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArticleRequest"];
            };
        };
        responses: {
            /** @description Article updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        article: components["schemas"]["Article"];
                    };
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    PostArticlesV1SlugPublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article published successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        article: components["schemas"]["Article"];
                    };
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    PostArticlesV1SlugUnpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article unpublished successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        article: components["schemas"]["Article"];
                    };
                };
            };
            /** @description Unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Article not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
