/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assets/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all assets at a path
         * @description Retrieves a list of all assets (files and folders) at the specified path.
         *
         *     **Authentication:**
         *     - Admin users (with admin scope) receive full asset details (AdminAsset type with id, createdBy, createdAt, status)
         *     - Public users (without admin scope) receive limited asset details (PublicAsset type without sensitive metadata)
         */
        get: {
            parameters: {
                query: {
                    /** @description Path to list assets from (use "/" for root) */
                    path: string;
                    /** @description Cursor for pagination */
                    cursor?: string;
                    /** @description Max number of assets to fetch */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of assets. Returns AdminAsset for authenticated admin users, PublicAsset for others. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Asset"][];
                            /**
                             * @description Total number of items in the folder
                             * @example 10
                             */
                            contentCount: number;
                            /** @example Y29uZ3JhdHMsIHlvdSBmb3VuZCB0aGUgZWFzdGVyIGVnZw== */
                            cursor?: string;
                            /** @example true */
                            hasNextPage: boolean;
                        };
                    };
                };
                /** @description Bad request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unknown server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a folder
         * @description Creates a new folder at the specified path. Admin only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Folder creation details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFolderRequest"];
                };
            };
            responses: {
                /** @description Folder created successfully. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            folder: components["schemas"]["AdminFolder"];
                        };
                    };
                };
                /** @description Bad request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Parent folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Folder already exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unknown server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/v1/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a presigned upload URL
         * @description Returns a presigned URL for uploading a file directly to S3. Admin only. The parent folder must exist.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Upload request details */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadRequest"];
                };
            };
            responses: {
                /** @description Presigned upload URL and asset ID. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                /** @description Bad request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Parent folder not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unknown server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/v1/by-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an asset
         * @description Get one asset (file or folder) by full path.
         *
         *     **Authentication:**
         *     - Admin users (with admin scope) receive full asset details (AdminAsset type with id, createdBy, createdAt, status)
         *     - Public users (without admin scope) receive limited asset details (PublicAsset type without sensitive metadata)
         */
        get: {
            parameters: {
                query: {
                    /** @description Full path to the asset (e.g., "/foo/bar.txt" or "/" for root) */
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The asset. Returns AdminAsset for authenticated admin users, PublicAsset for others. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            asset: components["schemas"]["Asset"];
                        };
                    };
                };
                /** @description Bad request. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Asset not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unknown server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete an asset
         * @description Delete an asset by full path. Admin only. Deleting a folder will fail if it still contains any files or subfolders.
         */
        delete: {
            parameters: {
                query: {
                    /** @description Full path to the asset (e.g., "/foo/bar.txt") */
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Asset deleted successfully. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request (e.g., folder not empty). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Asset not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unknown server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/v1/by-path/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm file upload
         * @description Confirms that a file has been uploaded to S3. Admin only.
         */
        post: {
            parameters: {
                query: {
                    /** @description Full path to the file (e.g., "/foo/bar.txt") */
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File confirmed successfully. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            file: components["schemas"]["AdminFile"];
                        };
                    };
                };
                /** @description Bad request (e.g., file not uploaded yet, or asset is not a file). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description File not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Version conflict (file was modified by another request). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unknown server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example file
         * @enum {string}
         */
        AssetType: "file" | "folder";
        Asset: components["schemas"]["AdminAsset"] | components["schemas"]["PublicAsset"];
        PublicFile: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            /**
             * @description Parent folder path
             * @example /images/carousel
             */
            path: string;
            /** @example hero-banner.png */
            name: string;
            /** @example Main hero banner for the homepage carousel */
            description?: string;
            /** @example image/png */
            contentType: string;
            /**
             * Format: int64
             * @description File size in bytes
             * @example 1048576
             */
            size: number;
            /**
             * @description CDN URL for the file
             * @example https://assets.icaa.world/abc123
             */
            url: string;
        };
        PublicFolder: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "folder";
            /**
             * @description Parent folder path
             * @example /images
             */
            path: string;
            /** @example carousel */
            name: string;
            /** @example Images for the homepage carousel */
            description?: string;
            /**
             * @description Number of items (files and folders) directly in this folder
             * @example 5
             */
            contentCount: number;
        };
        PublicAsset: components["schemas"]["PublicFile"] | components["schemas"]["PublicFolder"];
        AdminFile: components["schemas"]["PublicFile"] & {
            /**
             * Format: uuid
             * @example 00000000-0000-0000-0000-000000000000
             */
            readonly id: string;
            status: components["schemas"]["FileStatus"];
            /**
             * Format: date-time
             * @example 2025-08-19T18:46:53.185Z
             */
            readonly createdAt: string;
            /**
             * @description Email of the admin who uploaded the file
             * @example admin@icaa.world
             */
            readonly createdBy: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
        };
        AdminFolder: components["schemas"]["PublicFolder"] & {
            /**
             * Format: uuid
             * @example 00000000-0000-0000-0000-000000000000
             */
            readonly id: string;
            /**
             * Format: date-time
             * @example 2025-08-19T18:46:53.185Z
             */
            readonly createdAt: string;
            /**
             * @description Email of the admin who created the folder
             * @example admin@icaa.world
             */
            readonly createdBy: string;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "folder";
        };
        AdminAsset: components["schemas"]["AdminFile"] | components["schemas"]["AdminFolder"];
        /**
         * @example confirmed
         * @enum {string}
         */
        FileStatus: "pending" | "confirmed";
        CreateFolderRequest: {
            /**
             * @description Parent folder path (use "/" for root)
             * @example /images
             */
            path: string;
            /**
             * @description Name of the folder to create
             * @example carousel
             */
            name: string;
            /**
             * @description Optional description of the folder
             * @example Images for the homepage carousel
             */
            description?: string;
        };
        UploadRequest: {
            /**
             * @description Parent folder path where the file will be stored
             * @example /images/carousel
             */
            path: string;
            /**
             * @description Original file name
             * @example hero-banner.png
             */
            fileName: string;
            /**
             * @description MIME type of the file
             * @example image/png
             */
            contentType: string;
            /**
             * @description Optional description of the file
             * @example Main hero banner for the homepage carousel
             */
            description?: string;
        };
        UploadResponse: {
            /**
             * Format: uuid
             * @description ID of the file (use this to confirm the upload)
             * @example 00000000-0000-0000-0000-000000000000
             */
            fileId: string;
            /**
             * @description Presigned POST URL to upload the file to
             * @example https://icaa-assets.s3.amazonaws.com/
             */
            uploadUrl: string;
            /**
             * @description Form fields that must be included in the multipart/form-data POST request. The file itself must be added last with the field name 'file'.
             * @example {
             *       "key": "00000000-0000-0000-0000-000000000000",
             *       "Content-Type": "image/png",
             *       "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
             *       "X-Amz-Credential": "AKIAIOSFODNN7EXAMPLE/20240119/us-east-1/s3/aws4_request",
             *       "X-Amz-Date": "20240119T120000Z",
             *       "Policy": "eyJleHBpcmF0aW9uIjoiMjAyNC0wMS0xOVQxMzowMDowMFoiLCJjb25kaXRpb25zIjpbeyJidWNrZXQiOiJpY2FhLWFzc2V0cyJ9LFsiZXEiLCIka2V5IiwiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIl0sWyJlcSIsIiRDb250ZW50LVR5cGUiLCJpbWFnZS9wbmciXSxbImNvbnRlbnQtbGVuZ3RoLXJhbmdlIiwxLDI2MjE0NDAwXV19",
             *       "X-Amz-Signature": "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
             *     }
             */
            formFields: {
                [key: string]: string;
            };
            /**
             * Format: date-time
             * @description When the presigned URL expires
             * @example 2025-08-19T19:46:53.185Z
             */
            expiresAt: string;
        };
        /** @enum {string} */
        ErrorCode: "InternalError" | "LimitOutOfBounds" | "InvalidCursor" | "NotFound" | "EmptyBody" | "InvalidBody" | "AlreadyExists" | "InputValidationError" | "AuthError" | "AssetNotUploaded" | "FileTooLarge" | "FolderNotEmpty" | "ParentFolderNotFound" | "NotAFile" | "VersionConflict";
        Error: {
            /** @example InternalError */
            code: components["schemas"]["ErrorCode"];
            /** @example An unexpected error occurred. */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
