/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/donations/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a donation
         * @description Creates a new donation and returns a Stripe checkout session URL.
         */
        post: operations["PostDonationsV1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateDonationRequest: {
            /**
             * @description Amount in smallest currency unit (e.g., cents for USD)
             * @example 5000
             */
            amount: number;
            /**
             * @description ISO 4217 currency code
             * @example USD
             */
            currency: string;
            /**
             * Format: email
             * @example donor@example.com
             */
            donorEmail: string;
        };
        CreateDonationResponse: {
            /**
             * @description Stripe PaymentIntent client secret for embedded checkout
             * @example pi_1234567890_secret_xxxxxxxx
             */
            clientSecret: string;
        };
        Error: {
            /** @example BAD_REQUEST */
            error: string;
            /** @example Invalid donation amount */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    PostDonationsV1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Donation details */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDonationRequest"];
            };
        };
        responses: {
            /** @description Checkout session created successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDonationResponse"];
                };
            };
            /** @description Bad request. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown server error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
